ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.khaledamin.SerializationKt.configureSerialization
      com.khaledamin.controller.RoutingKt.configureRouting
      com.khaledamin.DatabaseKt.configureDatabase
    ]
  }
}